/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.socshared.template;

import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import ru.socshared.template.integration.AbstractIT;

import static org.junit.Assert.*;

public class ApplicationContextTest extends AbstractIT {

    @Test
    public void checkContextStarts() {

    }

}
